<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->webroot.'/modules/ratings/public/js/star_rating/jquery.ui.stars.min.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/common/qwebchannel.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/common/common.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/index/index.index.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/scrollpagination/jquery.scrollpagination.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/visibility/jquery-visibility.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/common/common.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/index/index.index.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/layout/jquery.qtip.min.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->webroot?>/modules/ratings/public/css/star_rating/jquery.ui.stars.css" />

<?php
if($this->layout == 'empty')
  {
  echo '<div class="viewWrapperSlicer">';
  }
else
  {
  echo '<div class="viewWrapperBrowser">';
  }
?>
  <div class="extensionsHeader">
    <div class="extensionsTitle">Slicer Extensions</div>
    <?php
    if($this->layout == 'empty')
      { ?>
      <div class="kwLogoContainer">
        <img alt="" class="kwLogo" src="<?php echo $this->moduleWebroot?>/public/images/kwlogo_100.png" />
      </div>
    <?php
      }
    else
      { ?>
      <div class="extensionFilterArea">
        <div class="extensionSelect">
          <select id="osSelect">
            <option value="win">Windows</option>
            <option value="linux">Linux</option>
            <option value="macosx">Mac OSX</option>
          </select>
          <svg width="12" height="12">
            <path d="m 2.5,5.5 4,4 4,-4"/>
          </svg>
        </div>
        <div class="extensionSelect">
          <select id="archSelect">
            <option value="amd64">64-bit</option>
            <option value="i386">32-bit</option>
          </select>
          <svg width="12" height="12">
            <path d="m 2.5,5.5 4,4 4,-4"/>
          </svg>
        </div>
	<label for="revisionInput">Revision: </label>
        <input type="text" id="revisionInput" class="extensionField" style="width: 4em;">
        <input type="text" id="searchInput" class="extensionField extensionSearchField">
        <br>
        <select id="releaseSelect" style="display:none;">
          <?php
          foreach($this->availableReleases as $release)
            {
            echo '<option value="'.$release.'">'.$release.'</option>';
            }
          ?>
        </select>
      </div>
    <?php
      } ?>
  </div>
  <div class="extensionsBody">
    <div class="extensionsBodyLeftColumn">
      <div class="categoryList">
        <div class="categoriesHeader">Categories</div>
        <ul id="categoriesList" class="categoriesList">
          <li id="categoryAll">All</li>
        </ul>
      </div>
    </div>
    <div class="extensionsBodyRightColumn">
      <div class="extensionList">
        <div class="paginationMessage"></div>
        <div class="loadingExtensions">
          <img alt="" src="<?php echo $this->coreWebroot?>/public/images/icons/loading.gif" /> Loading extensions
        </div>
        <div id="extensionsContainer">
        </div>
        
      </div>
    </div>
  </div>
</div>

<!-- TEMPLATE: extension -->
<div class="extensionWrapper" style="display: none;" id="extensionTemplate">
  <div class="extensionIconWrapper">
    <img width="128px" height="128px" alt="" src="" class="extensionIcon" />
  </div>
  <div class="extensionNameWrapper">
    <a href="javascript:;" class="extensionName"></a>
  </div>
  <div class="subtitleWrapper">
    <span class="subtitle"></span>
  </div>
  <div class="extensionRatings">
    <form>
      <input type="radio" name="avgrate" value="1"/>
      <input type="radio" name="avgrate" value="2"/>
      <input type="radio" name="avgrate" value="3"/>
      <input type="radio" name="avgrate" value="4"/>
      <input type="radio" name="avgrate" value="5"/>
      <input type="radio" name="avgrate" value="6"/>
      <input type="radio" name="avgrate" value="7"/>
      <input type="radio" name="avgrate" value="8"/>
      <input type="radio" name="avgrate" value="9"/>
      <input type="radio" name="avgrate" value="10"/>
    </form>
    <span class="totalVotes"></span>
  </div>
  <div class="extensionActionButtonWrapper">
    <input type="button" class="extensionActionButton" />
  </div>
</div>
