<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>

<p>
The <a target="_blank" href="http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Extensions/Catalog">
Slicer Extension Catalog</a> is hosted by <a target="_blank" href="http://www.kitware.com">Kitware<a> using the
<a target="_blank" href="http://midasplatform.org">Midas platform</a>.
The Extension Catalog can also be accessed via your web browser
<a target="_blank" href="http://slicer.kitware.com/midas3/slicerappstore">here</a>.
</p>

<p>
The continuous integration system for automatically building and uploading extensions on a nightly
basis is made possible by following
<a target="_blank" href="http://www.kitware.com/solutions/softwareprocess/softwareprocess.html">
Kitware software process</a> best practices. It leverages the CMake/CDash/Midas stack supported and developed by Kitware.
</p>

<p>If you are interested in delivering extensions or plugins to your application users by customizing your existing software process do not hesitate to contact us at</p>
<center>
  <a target="_blank" href="mailto:kitware@kitware.com">kitware@kitware.com</a>
</center>
<br/>
<center style="margin-top:1.1em">
  <a href="http://www.cdash.org"><img height="48" src="http://www.cdash.org/opensourcelogos/cdash100.png"/></a>
  <a href="http://www.midasplatform.org"><img height="48" src="http://midasplatform.org/MIDAS/img/MIDAS-PNG.png"/></a>
  <a href="http://www.cmake.org"><img height="48" src="http://www.cmake.org/opensourcelogos/cmake100.png"/></a>
</center>
<br/>
<small><pre>
This work was supported by NIH grant 3P41RR013218-12S1, NA-MIC, NAC and Slicer community.
</pre></small>
