<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>

<p>
The <a target="_blank" href="http://midasplatform.org">Midas server</a> supporting the
<a target="_blank" href="http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Extensions/Catalog">
Slicer Extensions Catalog</a> is hosted by <a target="_blank" href="http://www.kitware.com">Kitware<a>.
The Extension Catalog can also be accessed via your web browser
<a target="_blank" href="http://slicer.kitware.com/midas3/slicerappstore">here</a>.
</p>

<p>
The continuous integration system for automatically building and hosting extensions on a nightly
basis is made possible by following
<a target="_blank" href="http://www.kitware.com/solutions/softwareprocess/softwareprocess.html">
Kitware software process</a> best practices. It leverages the CMake, CTest, and CDash tools
supported and developed by Kitware.
</p>
