<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>

<p>
The <a target="_blank" href="http://www.slicer.org/slicerWiki/index.php/Documentation/Nightly/Extensions/Catalog">
Slicer Extensions Catalog</a> is hosted by <a target="_blank" href="http://www.kitware.com">Kitware<a> using 
<a target="_blank" href="http://midasplatform.org">Midas Platform</a>.
The Extensions Catalog can also be accessed via your web browser
<a target="_blank" href="http://slicer.kitware.com/midas3/slicerappstore">here</a>.
</p>

<p>
The continuous integration system for automatically building and uploading extensions on a nightly
basis is made possible by following
<a target="_blank" href="http://www.kitware.com/solutions/softwareprocess/softwareprocess.html">
Kitware software process</a> best practices. It leverages the <a target="_blank"
href="http://www.cmake.org">CMake</a>/<a target="_blank"
href="http://www.cdash.org">CDash</a>/<a target="_blank"
href="http://www.midasplatform.org">Midas</a> stack, supported and developed by Kitware.
</p>

<p>If you are interested in delivering extensions or plugins to users of your application
by customizing your existing software process, do not hesitate to contact us at</p>
<center>
  <a target="_blank" href="mailto:support@kitware.com">support@kitware.com</a>
</center>

<center style="margin-top:1.1em">
  <a style="margin: 0 5px 0 5px;" target="_blank" href="http://www.cmake.org"><img
    src="<?php echo $this->moduleWebroot?>/public/images/cmake48.png"/></a>
  <a style="margin: 0 5px 0 5px;" target="_blank" href="http://www.cdash.org"><img
    src="<?php echo $this->moduleWebroot?>/public/images/cdash48.png"/></a>
  <a style="margin: 0 5px 0 5px;" target="_blank" href="http://www.midasplatform.org"><img
    src="<?php echo $this->moduleWebroot?>/public/images/midas48.png"/></a>
</center>

<br/>
<center>
<small>
This work was supported by NIH Grant 3P41RR013218-12S1, NA-MIC, NAC, and the Slicer community.
</small>
</center>
