<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

if($this->slicerView)
  {
  // Get required jQuery
  echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/jquery.js"></script>';
  echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/jquery-ui.js"></script>';
  echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/jquery.treeTable.js"></script>';
  echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/jquery.qtip.min.js"></script>';
  echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/layout/midas.callback.js"></script>';
  echo '<script type="text/javascript" src="'.$this->moduleWebroot.'/public/js/extension/extension.view.js"></script>';
  echo '<script type="text/javascript" src="'.$this->webroot.'/modules/ratings/public/js/common/common.ratings.js"></script>';
  echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/jquery/jquery.jqplot.min.js"></script>';
  echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/jquery/jqplot/jqplot.barRenderer.min.js"></script>';
  echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/jquery/jqplot/jqplot.categoryAxisRenderer.min.js"></script>';
  echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/jquery/jqplot/jqplot.pointLabels.min.js"></script>';
  echo '<script type="text/javascript" src="'.$this->coreWebroot.'/public/js/jquery/jquery.autogrow-textarea.js"></script>';
  echo '<script type="text/javascript" src="'.$this->webroot.'/modules/ratings/public/js/star_rating/jquery.ui.stars.min.js"></script>';
  echo '<script type="text/javascript" src="'.$this->webroot.'/modules/comments/public/js/item/item.comments.js"></script>';
  }
else
  {
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.jqplot.min.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jqplot/jqplot.barRenderer.min.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jqplot/jqplot.categoryAxisRenderer.min.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jqplot/jqplot.pointLabels.min.js');
  $this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.autogrow-textarea.js');
  $this->headScript()->appendFile($this->moduleWebroot.'/public/js/extension/extension.view.js');
  $this->headScript()->appendFile($this->webroot.'/modules/ratings/public/js/star_rating/jquery.ui.stars.min.js');
  $this->headScript()->appendFile($this->webroot.'/modules/ratings/public/js/common/common.ratings.js');
  $this->headScript()->appendFile($this->webroot.'/modules/comments/public/js/item/item.comments.js');
  }
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/extension/extension.view.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/layout/jquery.qtip.min.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.jqplot.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->webroot?>/modules/ratings/public/css/star_rating/jquery.ui.stars.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->webroot?>/modules/comments/public/css/item/item.comments.css" />

<div id="container_main">
  <div id="extension_banner"> 
    <div class="title">
      <div class="extension_title"><?php echo $this->extension->getProductname()?></div>
      <div class="group_title">
        Contributor Names
      </div>
      <div class="category">
        <span id="categoryBreadcrumb">
          <a class="breadcrumbLink" href="<?php echo $this->webroot?>/slicerappstore<?php if($this->slicerView) echo '?slicerView'?>">Slicer Extensions</a>
        </span>
      </div>
    </div> 
    <div class="button_bar">
      <img qtip="+1 on Google+" src="<?php echo $this->moduleWebroot?>/public/images/googleplus.png" width="32" height="32" class="googlePlus"/>
      <img qtip="Tweet this" src="<?php echo $this->moduleWebroot?>/public/images/twitter.png" width="32" height="32" class="twitter"/>
      <img qtip="Like on Facebook" src="<?php echo $this->moduleWebroot?>/public/images/LikeButton.png" width="78" height="32" class="facebook" />
    </div>
  </div>
  <div class="left_column">
    <div class="icon_art">
      <img src="<?php echo $this->icon ?>" width="128" height="128" />
    </div>
    <div class="download_button">
      <input type="button" id="downloadButton" value="Install" />
    </div>
    <div class="info_list">
      <?php echo $this->extension->getItem()->getDownload() ?> downloads<br/>
    </div>
    <div class="rating_area">
      <?php echo $this->element('rating', 'ratings'); ?>
    </div>
    <div class="rating_scale">
    </div>
  </div>
  <div class="right_content">
    <div class="content_header">Description</div>
    <div class="description">
    Content for  class "description" Goes Here. Content for  class &quot;description&quot; Goes Here. Content for  class &quot;description&quot; Goes Here. Content for class "description" Goes Here. Content for class "description" Goes Here. Content for class "description" Goes Here. Content for class "description" Goes Here. Content for class "description" Goes Here.</div> 
    <div class="content_header">
      Screenshots
    </div>
    <div class="screenshots">
    Content for  class "screenshots" Goes Here. Content for  class &quot;screenshots&quot; Goes Here. Content for  class &quot;screenshots&quot; Goes Here. Content for  class &quot;screenshots&quot; Goes Here. Content for  class &quot;screenshots&quot; Goes Here. Content for  class &quot;screenshots&quot; Goes Here. Content for  class &quot;screenshots&quot; Goes Here. Content for  class &quot;screenshots&quot; Goes Here.</div>
    <div class="content_header">
      Tutorials
    </div>
    <div class="tutorials">
    Content for  class "tutorials" Goes Here. Content for  class &quot;tutorials&quot; Goes Here. Content for  class &quot;tutorials&quot; Goes Here. Content for  class &quot;tutorials&quot; Goes Here. Content for  class &quot;tutorials&quot; Goes Here. Content for  class &quot;tutorials&quot; Goes Here. Content for  class &quot;tutorials&quot; Goes Here. Content for  class &quot;tutorials&quot; Goes Here.</div>
    <div class="content_header">
      User Comments
    </div>
    <div class="reviews">
      <?php echo $this->element('comment', 'comments'); ?>
    </div>
  </div>
</div>

<!-- Pass json to our javascript -->
<div style="display: none;" id="jsonContent">
  <?php echo json_encode(array(
                        'slicerView' => $this->slicerView,
                        'extension' => $this->extension,
                        'item' => $this->extension->getItem(),
                        'icon' => $this->icon,
                        'global' => array('logged' => $this->logged,
                                          'webroot' => $this->webroot,
                                          'moduleWebroot' => $this->moduleWebroot,
                                          'coreWebroot' => $this->coreWebroot),
                        'modules' => array('ratings' => $this->ratings,
                                           'comments' => $this->comments)));
  ?>
</div>
