<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/

$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.jqplot.min.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jqplot/jqplot.barRenderer.min.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jqplot/jqplot.categoryAxisRenderer.min.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jqplot/jqplot.pointLabels.min.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.autogrow-textarea.js');
$this->headScript()->appendFile($this->coreWebroot.'/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/common/common.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/extension/extension.view.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/lightbox/jquery.lightbox-0.5.pack.js');
$this->headScript()->appendFile($this->moduleWebroot.'/public/js/imgliquid/imgLiquid-min.js');
$this->headScript()->appendFile($this->webroot.'/modules/ratings/public/js/star_rating/jquery.ui.stars.min.js');
$this->headScript()->appendFile($this->webroot.'/modules/ratings/public/js/common/common.ratings.js');
$this->headScript()->appendFile($this->webroot.'/modules/comments/public/js/item/item.comments.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/common/common.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/extension/extension.view.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/lightbox/jquery.lightbox-0.5.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/imgliquid/imgLiquid.js.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/layout/jquery.qtip.min.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/layout/jquery-ui.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.jqplot.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->webroot?>/modules/ratings/public/css/star_rating/jquery.ui.stars.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->webroot?>/modules/comments/public/css/item/item.comments.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->webroot?>/modules/ratings/public/css/item/item.ratings.css" />

<div class="category">
  <span id="categoryBreadcrumb">
    <a id="rootBreadcrumb" class="breadcrumbLink" href="">Slicer Extensions</a>
  </span>
</div>

<div id="container_main">
  <div id="extension_banner">
    <div class="title">
      <div class="extension_title"><?php echo $this->extension->getProductname()?></div>
      <div class="group_title">
        <?php echo $this->extension->getContributors() ?>
      </div>
    </div>
    <div class="button_bar">
      <!--
      <img qtip="+1 on Google+" src="<?php echo $this->moduleWebroot?>/public/images/googleplus.png" width="32" height="32" class="googlePlus"/>
      <img qtip="Tweet this" src="<?php echo $this->moduleWebroot?>/public/images/twitter.png" width="32" height="32" class="twitter"/>
      <img qtip="Like on Facebook" src="<?php echo $this->moduleWebroot?>/public/images/LikeButton.png" width="78" height="32" class="facebook" />
      -->
      <?php if($this->logged) { ?>
        <div class="logoutDiv"><a href="javascript:;" id="logoutLink">Logout</a></div>
      <?php } ?>
    </div>
  </div>
  <div class="left_column">
    <div class="icon_art">
      <img src="<?php echo $this->icon ?>" width="128" height="128" />
    </div>
    <div class="extensionActionButtonWrapper">
      <input type="button" class="extensionActionButton" value=""/>
    </div>
    <div class="info_list">
      <div class="info_item">
        Created <?php echo date('F j, Y', strtotime($this->extension->getItem()->getDateCreation())); ?>
      </div>
      <div class="info_item">
        <?php echo UtilityComponent::formatSize($this->extension->getItem()->getSizebytes()); ?>
      </div>
      <div class="info_item">
        <?php echo $this->extension->getItem()->getDownload() ?> downloads
      </div>
    </div>
    <div class="rating_area">
      <?php echo $this->element('rating', 'ratings'); ?>
    </div>
    <div class="rating_scale">
    </div>
  </div>
  <div class="right_content">
    <div class="content_header">
      Description
    </div>
    <div class="description">
      <?php echo htmlentities($this->extension->getDescription()) ?>
    </div>
    <?php
    if($this->extension->getHomepage() || $this->extension->getRepositoryUrl())
      { ?>
      <div class="content_header">
        Links
      </div>
      <div class="links">
        <?php
        if($this->extension->getHomepage())
          {
          echo '<div class="homepageContainer"><a target="_blank" href="'.$this->extension->getHomepage().'">';
          echo '<img alt="" src="'.$this->moduleWebroot.'/public/images/house_link.png" /> ';
          echo 'View home page</a></div>';
          }
        if($this->extension->getRepositoryUrl())
          {
          switch(strtolower($this->extension->getRepositoryType()))
            {
            case 'git':
              $icon = 'git';
              break;
            case 'svn':
              $icon = 'svn';
              break;
            default:
              $icon = 'default';
              break;
            }
          echo '<div class="repoLinkContainer"><a target="_blank" href="'.$this->extension->getRepositoryUrl().'">';
          echo '<img alt="" src="'.$this->moduleWebroot.'/public/images/repo/'.$icon.'.png" /> ';
          echo 'View source code</a></div>';
          }
        ?>
      </div>
    <?php 
      } ?>
    <div class="content_header">
      Screenshots
    </div>
    <div class="screenshots">
    </div>
    <div class="content_header">
      User Comments
    </div>
    <div class="reviews">
      <?php echo $this->element('comment', 'comments'); ?>
    </div>
  </div>
</div>

<!-- TEMPLATE: Screenshot -->
<div style="display: none;" class="screenshotContainer" id="screenshotTemplate">
  <a class="screenshotPreview" href="">
    <img class="screenshotPreview" alt="" src="" />
  </a>
</div>


<?php
if($this->layout == 'empty')
  { ?>
  <!-- TEMPLATE: login form -->
  <div id="loginFormTemplate" style="display:none;">
    <div class="loginError">
    </div>
    <form class="loginForm dialogForm" method="POST" action="<?php echo $this->webroot?>/user/ajaxlogin">
      <table>
        <tr><td>E-mail</td><td><input name="email" type="text" /></td></tr>
        <tr><td>Password</td><td><input name="password" type="password" /></td></tr>
        <tr><td></td><td><input type="submit" value="Login" /></td></tr>
      </table>
    </form>
    <div>
    Not registered? <a class="registerLink" href="javascript:;">Register</a>
    </div>
  </div>

  <!-- TEMPLATE: register form -->
  <div id="registerFormTemplate" style="display:none;">
    <div class="registerError">
    </div>
    <form class="registerForm dialogForm" method="POST" action="<?php echo $this->webroot?>/user/ajaxregister">
      <table>
        <tr><td>E-mail</td><td><input name="email" type="text" /></td></tr>
        <tr><td>First Name</td><td><input name="firstname" type="text" /></td></tr>
        <tr><td>Last Name</td><td><input name="lastname" type="text" /></td></tr>
        <tr><td>Password</td><td><input name="password1" type="password" /></td></tr>
        <tr><td>Confirm Password</td><td><input name="password2" type="password" /></td></tr>
        <tr><td></td><td><input type="submit" value="Register" /></td></tr>
      </table>
    </form>
    <div>
    Already registered? <a class="loginLink" href="javascript:;">Login</a>
    </div>
  </div>
<?php
  }
?>
